#### What are the inputs?
board setup
lawn is a string that tells you where the plants are.
zombies has when zombie appears, the row, and the health points. 

lawn is a list of strings
zombies is a list of lists, where the inner one is [enter move, row, hit points]

```
[
'2       ',
'  S     ',
'21  S   ',
'13      ',
'2 3     '],

[[0,4,28],[1,1,6],[2,0,10],[2,4,15],[3,2,16],[3,3,13]]],
```            


#### What is the desired output?
either number of moves when zombies penetrate defense, or None (zombies lose).


#### What are the steps of the game?

1. Parse the input
    - create an array?
    - maybe a matrix for the lawn?
    - could use a flag for if the zombie is still alive
    
2. Zombies take action
3. Plants shoot
4. Evaluate how many health zombies have left.
5. Record turn


In [1]:
import numpy as np

In [2]:
class Game:
    
    def __init__(self, inputs):
        self.game_over = False
        self.parse(inputs)
        self.turn = 0

    def parse(self, inputs):
        self.parse_lawn(inputs[0])
        self.parse_zombies(inputs[1])        
        
    def parse_lawn(self, lawn):
        '''
        convert string into an array that holds information about plants
        ----
        params:
            lawn: list of strings that describes the 'lawn'

        returns:
            None
        '''
        # Parse one line at a time?
        print('parsing the lawn')
        self.lawn = np.array([list(row) for row in lawn])
    
    def parse_zombies(self, zombies):
        '''
        convert list into a numpy array that holds information about zombies
        ----
        params:
            zombies: list of lists that contain integers describing the zombie

        returns:
            None
        '''    
        # we could use a dictionary {zombie_id: int, location: tuple (row,col), hp:int}
        # we could use a numpy array for the zombies with location by row/col and value = hp
        # we could leave as is, and reference it later
        print('parsing zombies')
        self.zombie_waiting_list = zombies
        self.zombies = np.zeros(self.lawn.shape)
        
    def play(self):
        '''
        plays game to completion
        
        '''
        while self.game_over is False:
            self.play_one_turn()

    def play_one_turn(self):
        '''
        plays one turn of the game
        
        '''
        print('Playing turn', self.turn)
        self.move_zombies()
        self.enter_zombies()
        self.plants_shoot()
        self.turn += 1
        print('Turn', self.turn)
        print('Lawn:')
        print(self.lawn)
        print('Zombies:')        
        print(self.zombies)       
            
    def enter_zombies(self):
        '''
        bring zombies onto the board if it's their turn
        '''
        # loop through zombie waiting list
        # if zombie[0] is this turn, move it onto board
        
        # for every zombie in the waiting list
        for zombie in self.zombie_waiting_list:
            # if it's the zombie's turn
            if zombie[0] == self.turn:
                print('Placing zombie', zombie, 'at row', zombie[1], 'on turn', self.turn, 'with', zombie[2], 'hp')
                # the row it should enter in is zombie[1]
                row = zombie[1]
                # place this zombie on the board at row, in the last column.
                # the value we are putting there is the zombie's health
                self.zombies[row, -1] = zombie[2] 
        
        
    def move_zombies(self):
        '''
        moves zombies forward
        '''
        print('Moving Zombies')
        # if the first item in zombie list is the right turn, then put it on the board
        if self.zombies[:, 0].sum() > 0:
            self.game_over = True
        else:
            # shift all zombies to the left one square
            new_board = np.zeros_like(self.zombies)
            new_board[:, :-1] = self.zombies[:, 1:]
            self.zombies = new_board

    
    def plants_shoot(self):
        '''
        makes all plants shoot
        shooting should decrease zombie hp
        'number' shooters go first
        then 'S' shooters, right to left then top to bottom
        
        '''
        print('Plants are shooting')
        self.number_shooters()
        self.s_shooters()
        
    def number_shooters(self):
        # if the row of shooter is row of zombie, then health points decrease by the amount shooter is
        # if shots > zombie hp, then overflow to next zombie
        # get shots per row, and do things to zombies based on that
        for row in range(self.lawn.shape[0]):
            # get number of shots
            # decrement zombie health by number of shots
            self.shots_shots_shots(row)
    
    def shots_shots_shots(self, row):
        '''
        handles shots on a single row.
        ---
        params:
            row: intger specifying row of the lawn numpy array
        '''
        shots = sum([int(item) for item in self.lawn[row] if item.isdigit()])
        print('Firing', shots, 'shots on row', row)
        
        # have we hit any zombies?
        
        while (shots > 0) & (sum(self.zombies[row, :]) > 0):
            # then we need to do shots
            for i, zombie in enumerate(self.zombies[row, :]):
                if zombie <= shots:
                    self.zombies[row, :][i] = 0
                    shots = shots - zombie            
                else:
                    self.zombies[row, :][i] = zombie - shots
                    shots = 0      
    
    def s_shooters(self):
        # 1. scan board from right to left and then top to bottom
        # 2. for each of these S shooters, shoot in three directions
        
        pass
    
    
    def get_s_shooters(self):
        
        for i in np.where(self.lawn == 'S'):    
        # output right most, then topmost
        
        pass
    
    
    def s_shots(self, pos):
        pass
    

In [3]:
sample_inputs = [[
'2       ',
'  S     ',
'21  S   ',
'13      ',
'2 3     '],
[
    # on round 0 (the first round), a zombie will appear in row 4.
    [0,4,28],
    # on round 1, a zombie will appear in row 1.
    [1,1,6],
    # on round 2, a zombie will appear in rows 0 and 4
    [2,0,10],
    [2,4,15],
    # on round 3, a zombie will appear in rows 2 and 3
    [3,2,16],
    [3,3,13]]]

game = Game(sample_inputs)

parsing the lawn
parsing zombies


In [13]:
np.where(game.lawn == 'S')

(array([1, 2]), array([2, 4]))

In [27]:
np.sort(np.where(game.lawn == 'S'), axis=1)

array([[1, 2],
       [2, 4]])

In [4]:
game.zombie_waiting_list

[[0, 4, 28], [1, 1, 6], [2, 0, 10], [2, 4, 15], [3, 2, 16], [3, 3, 13]]

In [5]:
game.zombies

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [6]:
zombie_board = game.play()

Playing turn 0
Moving Zombies
Placing zombie [0, 4, 28] at row 4 on turn 0 with 28 hp
Plants are shooting
Firing 2 shots on row 0
Firing 0 shots on row 1
Firing 3 shots on row 2
Firing 4 shots on row 3
Firing 5 shots on row 4
Turn 1
Lawn:
[['2' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' 'S' ' ' ' ' ' ' ' ' ' ']
 ['2' '1' ' ' ' ' 'S' ' ' ' ' ' ']
 ['1' '3' ' ' ' ' ' ' ' ' ' ' ' ']
 ['2' ' ' '3' ' ' ' ' ' ' ' ' ' ']]
Zombies:
[[ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. 23.]]
Playing turn 1
Moving Zombies
Placing zombie [1, 1, 6] at row 1 on turn 1 with 6 hp
Plants are shooting
Firing 2 shots on row 0
Firing 0 shots on row 1
Firing 3 shots on row 2
Firing 4 shots on row 3
Firing 5 shots on row 4
Turn 2
Lawn:
[['2' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' 'S' ' ' ' ' ' ' ' ' ' ']
 ['2' '1' ' ' ' ' 'S' ' ' ' ' ' ']
 ['1' '3' ' ' ' ' ' ' ' ' ' ' ' ']
 ['2' ' ' '3' ' ' ' ' '

In [ ]:
new_board = np.zeros_like(zombie_board)
new_board[:, :-1] = zombie_board[:, 1:]
new_board

In [ ]:
# zombie_board[:, 0].sum() > 0 then zombies win

In [ ]:
# check if this game object instance has the lawn information stored
game.lawn.shape


In [ ]:
sample_zombies = sample_inputs[1]
sample_zombies

In [ ]:
#desired:
#  0, 0,  10, 0 
#  0, 6,  0,  0
#  0, 0,  0, 16
#  0, 0,  0, 13
# 28, 0, 15,  0



In [ ]:
game.lawn

In [ ]:
# how do we find out how many shots to do on row 2?

shots = 0
for item in game.lawn[2]:
    if item.isdigit():
        shots += int(item)
shots

In [ ]:
sum([int(item) for item in game.lawn[2] if item.isdigit()])

In [ ]:
zombie_row = game.zombies[4].copy()

shots = 31

while (shots > 0) & (sum(zombie_row) > 0):
    # then we need to do shots
    for i, zombie in enumerate(zombie_row):
        if zombie <= shots:
            zombie_row[i] = 0
            shots = shots - zombie            
        else:
            zombie_row[i] = zombie - shots
            shots = 0

zombie_row
            
        

In [ ]:
game.zombies[4]

In [ ]:
shots